### PR TITLE
Thai SDA hymnal and other hymnal content edits

### PR DESCRIPTION
**Pull request by danielbair**
This data has differences from the main content:
1. Lyrics/Content is stored per verse/refrain
2. Thematic List is stored as a list of numbers not as a range.
3. Additional records per hymn such as authors, time signature, key signature.

### CODE REVIEW

**Comment by danielbair** [comment]
BTW, I don't know the date of publication of the Thai SDA hymnal, but I do know that it must have been before 1985 as it references page numbers from the 1940 English SDA hymnal.

**Comment by danielbair** [comment]
And I don't have any clue on the date of publication of the French or Burmese hymnals either.

**Comment by danielbair** [comment]
I haven't yet found where you render/display the hymn content, but to use the json content I have submitted here, it would need a new render-er for the lyrics content to assemble the verse/refrain into html.

This is what have working in JavaScript/TypeScript for ionic/cordova:

```
  public getHymnById(id: number): Hymn {
    const hymn_id = id-1;
    console.log("getHymnById: ",hymn_id);
    if (this.hymns.length == 0) {
      const hymn = {"id":id,
                    "title":"Lorem ipsum",
                    "original_title":"Original title",
                    "lyrics":[],
                    "lyrics_text":"<p>Lorem ipsum dolor sit amet,</p>\n<blockquote><i>consectetur adipiscing elit.</i></blockquote>"};
      return hymn;
    }
    const hymn = this.hymnal.hymns[hymn_id];
    this.hymn = JSON.parse(JSON.stringify(hymn));
    this.refrain = "";
    this.lyrics = "";
    let num_keys: number = Object.keys(this.hymn.lyrics).length;
    for (let key = 0; key < num_keys; key++) {
      let num_key: number = key;
      let ref_key: number = key+1;
      let max_key: number = num_keys-1;
      if (this.hymn.lyrics[num_key].line == "ref" && num_key == 0) {
        this.refrain = "<blockquote><i>" + this.hymn.lyrics[num_key].text + "</i></blockquote>\n";
        this.lyrics += this.refrain;
      }
      if (ref_key<max_key && this.hymn.lyrics[ref_key].line == "ref") {
        this.refrain = "<blockquote><i>" + this.hymn.lyrics[ref_key].text + "</i></blockquote>\n";
      }
      if (this.hymn.lyrics[num_key].line != "ref") {
        this.lyrics += "<p>" + this.hymn.lyrics[num_key].line + ". " + this.hymn.lyrics[num_key].text + "</p>\n" + this.refrain;
      }
    }
    this.hymn.lyrics_text = this.lyrics;
    return this.hymn;
  }
```

**Comment by isax5** [comment]
Let me try a few things during this week because I'm trying to update the Xamarin version,
Anyway send the PR to '/releases/sprint03'

**Comment by danielbair** [comment]
Ok, will do.

**Comment by danielbair** [comment]
Closing with https://github.com/isax5/Hymnal-Xamarin/pull/125

**Pull request closed without merging**
