### PR TITLE
Releases/sprint03

### PR DESCRIPTION
**Pull request by isax5**

### CODE REVIEW

**Comment by thebiblelover7** [comment]
@isax5 Where can I test the builds from the `development` branch? Or at least how can I build it manually? I'd like to test this new build :)

**Comment by isax5** [comment]
Actually you can build it just using Visual Studio 2019 or 2022 on Windows or Mac
Anyway, I'm going to send a beta tomorrow or on thursday 
You can join the beta testing program using the information here: https://github.com/isax5/Hymnal-Xamarin#tests

**Comment by isax5** [comment]
The testing program for iOS may not be available until there is a new release

**Comment by thebiblelover7** [comment]
@isax5 Thanks! I try not to use the Google Play Store, so I'll try to build manually... thanks for such a great app!

**Pull request merged**
